### ISSUE TITLE
Move play queue entries up/down

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#40]
Currently, you can only remove play queue entries, and append new ones to the end of the queue. It would be nice if you could move entries up/down the queue.

(Or maybe I'm doing it wrong and should use temporary playlists instead of the play queue for "complicated" queues?)

**Comment by cmdrkotori** [comment]
I plan to implement a widget for this that will show the global quick queue. This should allow manipulating item order with the mouse using drag/drop move actions.

**Comment by wm4** [comment]
Sounds great.

**Comment by cmdrkotori** [comment]
Sorry about the wait, I had depression.

**Comment by wm4** [comment]
Thanks!

The quick queue looks nice. Is there a key binding to toggle the queue (like the quick queue button below the playlist)?

Also I happened to play around with the "Queue Visible" menu entry. I'm not sure if it was added recently. If you do the following, the player freezes:
1. queue a playlist entry
2. hit "ctrl+shift+q" twice (or click the menu entry twice)
3. it freezes
Should I report this separately?

Also I'd like the ability to move playlist entries up and down with the keyboard. Maybe when using Ctrl+Up/Ctrl+Down.

Still using mpc-qt as my music player.

**Comment by cmdrkotori** [comment]
Ctrl-shift-q should be fixed now, I'll get to the keyboard combos in a bit.

**Comment by wm4** [comment]
Just tried this. Unfortunately still seems to freeze when hitting ctrl+shift+q again to hide the queue.

**Comment by cmdrkotori** [comment]
ctrl+shift+q works on my machine.

btw the keyboard shortcuts you suggested are implemented now except for the ctrl+up and ctrl+down, which I need to put more thought into.

**Comment by wm4** [comment]
> ctrl+shift+q works on my machine.

Definitely still broken here. It freezes when making the queue invisible again. I can try debugging it tomorrow or so.

> btw the keyboard shortcuts you suggested are implemented now except for the ctrl+up and ctrl+down, which I need to put more thought into.

Thanks, works for me. Having ctrl+up/down would be nice too.

**Comment by wm4** [comment]
OK, it doesn't freeze up forever. It just takes a while. With 15k entries, it takes 10 seconds to unfreeze. That was enough to make me give up. Maybe some unintentionally quadratic runtime complexity?

Here's a backtrace from hitting ctrl+c while frozen (sorry no Qt debug symbols here):

```
#0  0x00007ffff6c10cb0 in QVariant::QVariant(QVariant const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff775b4e4 in QListWidgetItem::data(int) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff775b1e3 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff6b77387 in QAbstractItemModel::match(QModelIndex const&, int, QVariant const&, int, QFlags<Qt::MatchFlag>) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff775d42d in QListWidget::findItems(QString const&, QFlags<Qt::MatchFlag>) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00005555555ba0b0 in QDrawnPlaylist::removeItem(QUuid) ()
#6  0x00005555555d4deb in PlaylistWindow::visibleToQueue() ()
#7  0x00007ffff6bfc85e in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff74ad162 in QAction::triggered(bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff74afb50 in QAction::activate(QAction::ActionEvent) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff74b04cc in QAction::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff74b3b2c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---c
#12 0x00007ffff74bb2e1 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff6bd08f0 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff6f45198 in QShortcutMap::dispatchEvent(QKeyEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#15 0x00007ffff6f45259 in QShortcutMap::tryShortcut(QKeyEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff6efdc5d in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#17 0x00007ffff6f15144 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#18 0x00007ffff6f1a665 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#19 0x00007ffff6ef861b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#20 0x00007fffdef884e0 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#21 0x00007fffec2e97f7 in g_main_context_dispatch ()
```

**Comment by cmdrkotori** [comment]
Yeah, I just reproduced it. Adding is fast, removal not so fast. Quadratic time is introduced by the ui mirroring process. I'll give this another think about the best way handle stuff like this going forwards, perhaps a slight redesign of the drawn playlist implementation.

**Comment by wm4** [comment]
Works for me, thanks.
